### ISSUE TITLE
Set up contributing.md

### ISSUE THREAD

**Issue by asunwoo98** [nyu-software-engineering/ar-mini-games#13]
From https://github.com/nyu-software-engineering/ar-mini-games/issues/10

**Comment by koktavy** [comment]
We need to establish a schedule for standup meetings. At least documented _4 per week_. These will be less than 15 minutes, and foster communication between us.

We each answer: 
* What did you do since the last standup, and is it finished?
* What you are working on now?
* What problems/blockers do you have, if any?

What does documented mean?
* when and where the meeting took place
* who participated in-person
* who participated remotely
* who participated asynchronously
* who did not participate at all (those who participated must document this, it should be written in the Team Norms that all will be honest about this)
* what each member's answers to the 3 questions were

This documentation is posted to our standups Slack channel.

This schedule should be added to CONTRIBUTING.md. The Quip group has a [nice example](https://github.com/nyu-software-engineering/quip-thinking/blob/master/CONTRIBUTING.md) of this.

I propose we discuss this over Slack ASAP.
