### ISSUE TITLE
Learn Unity - Antony

### ISSUE THREAD

**Issue by asunwoo98** [nyu-software-engineering/ar-mini-games#9]
As a developer I want to learn Unity so that I can help with developing the game.

## Estimate of work
* M

## Acceptance criteria
- [x] Create a new project 
- [x] Learn physics
- [x] Follow some Unity site's tutorial

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-augmented-reality-rpg - generally nice work with these issues, even though there are too few of them.  Don't forget to assign every issue in your task board to one or more of your team members.  And also, since each of you have to do these spikes individually, there should really be duplicates of these so that you can all manage the progress of your own internal learning.  One person learning Unity and moving this issue to the Done column does not mean the others are also done.
